name             'rogue'
description      'Installs/Configures the ROGUE JCTD project'
maintainer       'ROGUE-JCTD'
maintainer_email 'rogue@lmnsolutions.com'
description      'Installs/Configures rogue'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.4'

depends 'nginx'
depends 'apt'
depends 'build-essential'
depends 'git'
depends 'python'
depends 'openssl'
depends 'hostsfile'
depends 'database'
depends 'java'
depends 'tomcat', '1.0.1'
depends 'postgresql', '3.4.24'
depends 'supervisord'
depends 'runit'
depends 'rabbitmq'
depends 'chef-vault'
